### ISSUE TITLE
Investigate the strange behavior of tests

### ISSUE THREAD

**Issue by rianby64** [rianby64/arca-ws-jsonrpc#1]
Currently if execute tests several times, then the result may vary inconsistently.

```
$ go test -test.timeout 2s
2018/12/14 21:53:55 connecting EOF
2018/12/14 21:53:55 EOF
panic: test timed out after 2s

goroutine 66 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000128000, 0x70bf79, 0xe, 0x71e918, 0x477901)
	/usr/lib/golang/src/testing/testing.go:879 +0x37a
testing.runTests.func1(0xc0000f2000)
	/usr/lib/golang/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc0000f2000, 0xc00008fe08)
	/usr/lib/golang/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00000c340, 0x936560, 0xe, 0xe, 0x40d25f)
	/usr/lib/golang/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc0000f0000, 0x0)
	/usr/lib/golang/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:68 +0x13d

goroutine 51 [chan receive]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.Test_Broadcast(0xc000128000)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/stuff_test.go:182 +0x2bb
testing.tRunner(0xc000128000, 0x71e918)
	/usr/lib/golang/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:878 +0x353

goroutine 52 [chan send]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).Broadcast(0xc00012c040, 0xc000112050)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:85 +0xa2
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.Test_Broadcast
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/stuff_test.go:180 +0x270

goroutine 31 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection.func1(0xc00000c860, 0xc0000dab00)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:74 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:73 +0x4d

goroutine 9 [chan receive]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).tickResponse(0xc00000c3a0, 0xc0000da580)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:93 +0xba
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).listenAndResponse
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:126 +0xd5

goroutine 11 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection.func1(0xc00000c3a0, 0xc0000da580)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:74 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:73 +0x4d

goroutine 15 [chan receive (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).tickResponse(0xc00000c540, 0xc0000da6e0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:93 +0xba
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).listenAndResponse
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:126 +0xd5

goroutine 16 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection.func1(0xc00000c540, 0xc0000da6e0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:74 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:73 +0x4d

goroutine 20 [chan receive (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).tickResponse(0xc00000c5e0, 0xc0000da840)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:93 +0xba
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).listenAndResponse
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:126 +0xd5

goroutine 21 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection.func1(0xc00000c5e0, 0xc0000da840)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:74 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:73 +0x4d

goroutine 24 [chan receive]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).tickResponse(0xc00000c6a0, 0xc0000da9a0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:93 +0xba
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).listenAndResponse
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:126 +0xd5

goroutine 26 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection.func1(0xc00000c6a0, 0xc0000da9a0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:74 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:73 +0x4d
exit status 2
FAIL	_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca	2.006s
```

```
$ go test -test.timeout 2s
2018/12/14 21:55:28 connecting EOF
2018/12/14 21:55:28 EOF
2018/12/14 21:55:28 connecting EOF
PASS
ok  	_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca	0.003s
```

```
$ go test -test.timeout 2s
2018/12/14 21:55:30 connecting EOF
2018/12/14 21:55:30 EOF
2018/12/14 21:55:30 connecting EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x65ef09]

goroutine 49 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc00014a420, 0xc000128480, 0xc00013e870)
	/home/rianby64/.go/src/github.com/gorilla/websocket/conn.go:331 +0x29
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.setupGlobals.func4(0xc00014a420, 0xc0001460f0, 0xc00014a420)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/init.go:34 +0x2b
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.(*JSONRPCServerWS).closeConnection(0xc0001422c0, 0xc00014a420, 0xc00013c500, 0x13e625)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/implementation.go:77 +0x89
_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.Test_Broadcast.func2(0xc0001422c0, 0xc00014a420, 0xc00014a580)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/stuff_test.go:196 +0x35
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud/arca.Test_Broadcast
	/home/rianby64/Go/arca-ws-jsonrpc-crud/arca/stuff_test.go:195 +0x43f
exit status 2
FAIL	_/home/rianby64/Go/arca-ws-jsonrpc-crud/arca	0.006s
```

Any set of tests MUST follow three principles
- Isolation
- Order independ
- Repeatedly run returns the same result

The third principle here looks to be broken...

**Comment by rianby64** [comment]
```
go test -v  -test.count 10 -test.timeout 2s -run ^Test_Broadcast$ 
=== RUN   Test_Broadcast
--- PASS: Test_Broadcast (0.00s)
    stuff_test.go:163: Test Broadcast
=== RUN   Test_Broadcast
--- PASS: Test_Broadcast (0.00s)
    stuff_test.go:163: Test Broadcast
=== RUN   Test_Broadcast
--- PASS: Test_Broadcast (0.00s)
    stuff_test.go:163: Test Broadcast
=== RUN   Test_Broadcast
--- PASS: Test_Broadcast (0.00s)
    stuff_test.go:163: Test Broadcast
=== RUN   Test_Broadcast
--- PASS: Test_Broadcast (0.00s)
    stuff_test.go:163: Test Broadcast
=== RUN   Test_Broadcast
panic: test timed out after 2s

goroutine 52 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000f6c00, 0x70f6e7, 0xe, 0x722858, 0x477901)
	/usr/lib/golang/src/testing/testing.go:879 +0x37a
testing.runTests.func1(0xc0000f6b00)
	/usr/lib/golang/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc0000f6b00, 0xc000091e08)
	/usr/lib/golang/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00000c300, 0x93cbe0, 0x1b, 0x1b, 0x40d25f)
	/usr/lib/golang/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc0000f0000, 0x0)
	/usr/lib/golang/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:94 +0x13d

goroutine 43 [chan receive]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.Test_Broadcast(0xc0000f6c00)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff_test.go:181 +0x2c2
testing.tRunner(0xc0000f6c00, 0x722858)
	/usr/lib/golang/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:878 +0x353

goroutine 18 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc000064840, 0xc0000da420)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 20 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc0000648c0, 0xc0000da6e0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 19 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc000064840, 0xc0000da580)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 67 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc000064a40, 0xc0000db080)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 23 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc000064940, 0xc0000dab00)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 22 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc000064940, 0xc0000da9a0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 21 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc0000648c0, 0xc0000da840)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 50 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc0000649c0, 0xc0000dac60)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 51 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc0000649c0, 0xc0000dadc0)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 66 [chan send (nil chan)]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection.func1(0xc000064a40, 0xc0000daf20)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:27 +0x61
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).closeConnection
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:26 +0x4d

goroutine 44 [chan send]:
_/home/rianby64/Go/arca-ws-jsonrpc-crud.(*JSONRPCServerWS).Broadcast(0xc000064ac0, 0xc000010410)
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff.go:38 +0xa2
created by _/home/rianby64/Go/arca-ws-jsonrpc-crud.Test_Broadcast
	/home/rianby64/Go/arca-ws-jsonrpc-crud/stuff_test.go:179 +0x277
exit status 2
FAIL	_/home/rianby64/Go/arca-ws-jsonrpc-crud	2.007s
```
